// Mocks generated by Mockito 5.4.6 from annotations
// in quadycons/test/domain/use_cases/clean_last_registrations_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:quadycons/domain/entities/pending_registration.dart' as _i4;
import 'package:quadycons/domain/entities/project.dart' as _i5;
import 'package:quadycons/domain/entities/registration_result.dart' as _i6;
import 'package:quadycons/domain/repositories/synchronization_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SynchronizationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSynchronizationRepository extends _i1.Mock
    implements _i2.SynchronizationRepository {
  @override
  _i3.Future<List<_i4.PendingRegistration>> getPendingRegistrations(
    List<_i5.Project>? projects,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingRegistrations, [projects]),
            returnValue: _i3.Future<List<_i4.PendingRegistration>>.value(
              <_i4.PendingRegistration>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.PendingRegistration>>.value(
                  <_i4.PendingRegistration>[],
                ),
          )
          as _i3.Future<List<_i4.PendingRegistration>>);

  @override
  _i3.Future<List<_i6.RegistrationResult>> synchronize(
    List<_i4.PendingRegistration>? registrations,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#synchronize, [registrations]),
            returnValue: _i3.Future<List<_i6.RegistrationResult>>.value(
              <_i6.RegistrationResult>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i6.RegistrationResult>>.value(
                  <_i6.RegistrationResult>[],
                ),
          )
          as _i3.Future<List<_i6.RegistrationResult>>);

  @override
  _i3.Future<void> markAsSynchronized(
    List<_i4.PendingRegistration>? registrations,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markAsSynchronized, [registrations]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeRegistrations(List<int>? attendancesIds) =>
      (super.noSuchMethod(
            Invocation.method(#removeRegistrations, [attendancesIds]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
